trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: 'vsprojects/pcsx-redux.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    maximumCpuCount: true
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    Contents: |
      vsprojects/Release/*.exe
      vsprojects/Release/*.dll
    TargetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
