trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: 'vsprojects/pcsx-redux.sln'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: CopyFiles@2
  inputs:
    Contents: |
      LICENSE
      i18n/*.po
    TargetFolder: '$(build.artifactStagingDirectory)/assets'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: 'x86'
    maximumCpuCount: true
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    Contents: |
      vsprojects/Release/*.exe
      vsprojects/Release/*.dll
    TargetFolder: '$(build.artifactStagingDirectory)/binaries'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: 'x64'
    maximumCpuCount: true
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    Contents: |
      vsprojects/x64/Release/*.exe
      vsprojects/x64/Release/*.dll
    TargetFolder: '$(build.artifactStagingDirectory)/binaries'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*.exe
      !**\pcsx-redux.exe
    searchFolder: '$(System.DefaultWorkingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
