name: macOS CI

on: [push]

jobs:
  macos-build-and-test:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: ./.github/scripts/install-brew-dependencies.sh
    - name: Fetch submodules
      run: git submodule update --init --recursive
    - name: Apply zstr patch
      run: patch -d third_party/zstr/ -p1 < .github/zstr_strict_fstream_darwin_fix.patch
    - name: Build pcsx-redux
      run: make -j2
