name: macOS CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-openbios:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: n1hility/cancel-previous-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Fetch submodules
      run: git submodule update --init --recursive
    - name: Install dependencies
      run: sudo apt-get install -y g++-mipsel-linux-gnu
    - name: Build OpenBIOS
      run: make -C src/mips/openbios -j2
    - name: Install OpenBIOS
      run: make install-openbios DESTDIR=PCSX-Redux.app/Contents/Resources
    - name: Upload results for MacOS build job
      uses: actions/upload-artifact@v2
      with:
        name: App
        path: PCSX-Redux.app/

  macos-build-and-test:
    runs-on: macOS-latest
    needs: build-openbios
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: ./.github/scripts/install-brew-dependencies.sh
    - name: Fetch submodules
      run: git submodule update --init --recursive
    - name: Build pcsx-redux
      run: make -j2
    - name: Download OpenBIOS build
      uses: actions/download-artifact@v2
      with:
        name: App
    - name: Bundle
      run: ./.github/scripts/create-app.sh
    - name: Create DMG
      run: |
        export BUILD=`git rev-parse HEAD | cut -c 1-8`
        mkdir dmgdir
        mv PCSX-Redux.app dmgdir
        hdiutil create -volname PCSX-Redux-$BUILD -srcfolder dmgdir -ov -format UDZO PCSX-Redux-$BUILD.dmg
    - name: Upload DMG
      uses: actions/upload-artifact@v2
      with:
        name: Dmg
        path: '**/*.dmg'

  publish-app:
    runs-on: ubuntu-latest
    needs: macos-build-and-test
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true
    - name: Download DMG
      uses: actions/download-artifact@v2
      with:
        name: Dmg
    - name: Distribute app
      env:
        APPCENTER_ACCESS_TOKEN: ${{ secrets.MACOS_APPCENTER_ACCESS_TOKEN }}
      run: |
        npm install -g appcenter-cli
        export BUILD=`git rev-parse HEAD | cut -c 1-8`
        appcenter distribute release -b $BUILD -f PCSX-Redux-$BUILD.dmg -g 45026cdd-80b8-49e4-b836-974b723f7730 -a grumpycoders/pcsx-redux-macos --disable-telemetry
