name: macOS CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  macos-build-and-test:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: ./.github/scripts/install-brew-dependencies.sh
    - name: Fetch submodules
      run: git submodule update --init --recursive
    - name: Build pcsx-redux
      run: make -j2
